# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 16:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('btp_rate', models.FloatField()),
                ('currency_type', models.IntegerField(choices=[(1, 'BTP'), (2, 'ETHER')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EtherScanTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockNumber', models.TextField(blank=True)),
                ('timeStamp', models.TextField(blank=True)),
                ('hash', models.TextField(blank=True)),
                ('nonce', models.TextField(blank=True)),
                ('blockHash', models.TextField(blank=True)),
                ('transactionIndex', models.TextField(blank=True)),
                ('e_from', models.TextField(blank=True)),
                ('e_to', models.TextField(blank=True)),
                ('value', models.TextField(blank=True)),
                ('gas', models.TextField(blank=True)),
                ('gasPrice', models.TextField(blank=True)),
                ('isError', models.TextField(blank=True)),
                ('txreceipt_status', models.TextField(blank=True)),
                ('input', models.TextField(blank=True)),
                ('contractAddress', models.TextField(blank=True)),
                ('cumulativeGasUsed', models.TextField(blank=True)),
                ('gasUsed', models.TextField(blank=True)),
                ('confirmations', models.TextField(blank=True)),
                ('btp_rate', models.FloatField(default=3072)),
                ('bonus_percent', models.FloatField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.BigIntegerField(unique=True)),
                ('address', models.TextField(blank=True, verbose_name='btc_address')),
                ('callback_url', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.TextField()),
                ('value', models.FloatField(default=0.0)),
                ('is_old_adress', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('btp_rate', models.FloatField(default=53000)),
                ('bonus_percent', models.FloatField(default=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='NotifyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingInvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.TextField()),
                ('value', models.FloatField(default=0.0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='TokenSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_sale', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ico', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
