# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttable',
            name='btp_rate',
            field=models.FloatField(verbose_name='GLC rate'),
        ),
        migrations.AlterField(
            model_name='discounttable',
            name='currency_type',
            field=models.IntegerField(choices=[(1, 'GLC'), (2, 'ETHER')], default=1),
        ),
        migrations.AlterField(
            model_name='etherscantransaction',
            name='btp_rate',
            field=models.FloatField(default=3072, verbose_name='GLC rate'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='btp_rate',
            field=models.FloatField(default=53000, verbose_name='GLC rate'),
        ),
    ]
