# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoicepayment_is_old_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtherScanTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockNumber', models.TextField(blank=True)),
                ('timeStamp', models.TextField(blank=True)),
                ('hash', models.TextField(blank=True)),
                ('nonce', models.TextField(blank=True)),
                ('blockHash', models.TextField(blank=True)),
                ('transactionIndex', models.TextField(blank=True)),
                ('e_from', models.TextField(blank=True)),
                ('e_to', models.TextField(blank=True)),
                ('value', models.TextField(blank=True)),
                ('gas', models.TextField(blank=True)),
                ('gasPrice', models.TextField(blank=True)),
                ('isError', models.TextField(blank=True)),
                ('txreceipt_status', models.TextField(blank=True)),
                ('input', models.TextField(blank=True)),
                ('contractAddress', models.TextField(blank=True)),
                ('cumulativeGasUsed', models.TextField(blank=True)),
                ('gasUsed', models.TextField(blank=True)),
                ('confirmations', models.TextField(blank=True)),
            ],
        ),
    ]
