# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='referal_bonus',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
